version: '{build}'
image: Visual Studio 2015
configuration: Release
pull_requests:
  do_not_increment_build_number: true

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: +iNEfrl8Z7zx4r5O8LqhnQORqpE2LBu8+DoQqn4Sgx0JEadeg8ZF8vfsC1HaJOhJ

cache:
  - packages -> **\packages.config

install:
  - ps: choco install gitversion.portable -pre -y

assembly_info:
  patch: true

before_build:
  - nuget restore src/DatabaseConnections.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo /b (get-item env:APPVEYOR_REPO_BRANCH).Value

build:
  project: src/DatabaseConnections.sln

after_build:
  - cmd: >-
      nuget pack src\DatabaseConnections\DatabaseConnections.csproj -IncludeReferencedProjects -Build -Version "%GitVersion_NuGetVersion%" -Prop "target=%CONFIGURATION%"

      nuget pack src\DatabaseConnections.Postgres\DatabaseConnections.Postgres.csproj -IncludeReferencedProjects -Build -Version "%GitVersion_NuGetVersion%" -Prop "target=%CONFIGURATION%"

      nuget pack src\DatabaseConnections.SQLite\DatabaseConnections.SQLite.csproj -IncludeReferencedProjects -Build -Version "%GitVersion_NuGetVersion%" -Prop "target=%CONFIGURATION%"

test_script:
  - nuget install NUnit.ConsoleRunner -Version 3.6.1 -OutputDirectory tools
  - nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
  - nuget install coveralls.net -Version 0.7.0 -OutputDirectory tools
  - ps: >-
      .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe
      -register:user
      -filter:"+[*]* -[*]*Wrapper -[*.Tests]*"
      -target:"tools\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe"
      -targetargs:"/domain:single src\DatabaseConnections.Tests\bin\$env:CONFIGURATION\DatabaseConnections.Tests.dll src\DatabaseConnections.Postgres.Tests\bin\$env:CONFIGURATION\DatabaseConnections.Postgres.Tests.dll src\DatabaseConnections.SQLite.Tests\bin\$env:CONFIGURATION\DatabaseConnections.SQLite.Tests.dll"
      -output:opencoverCoverage.xml

      $coveralls = (Resolve-Path "tools/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()

      & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor

artifacts:
  - path: '*.nupkg'
    name: NuGet

deploy:
  - provider: Environment
    name: EKM PreRelease NuGet Feed
    on:
      branch: master
  - provider: Environment
    name: Public NuGet Feed
    on:
      appveyor_repo_tag: true
